apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoria-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoria-metrics
  template:
    metadata:
      labels:
        app: victoria-metrics
    spec:
      containers:
      - name: victoria-metrics
        image: "{{ .Values.victoriametrics.image.repository }}:{{ .Values.victoriametrics.image.tag }}"
        args:
        - "-retentionPeriod={{ .Values.victoriametrics.retentionPeriod }}"
        ports:
        - containerPort: 8428
          name: http
        resources:
          {{- toYaml .Values.victoriametrics.resources | nindent 10 }}
        volumeMounts:
        - name: storage
          mountPath: /storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: victoria-metrics-pvc