apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: victoria-metrics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.victoriametrics.persistence.size }}