{{- if .Values.vmagent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: vmagent
spec:
  type: NodePort
  selector:
    app: vmagent
  ports:
  - port: 8429
    targetPort: http
    nodePort: {{ .Values.vmagent.nodePort }}
{{- end }}