mad:
  victoriametrics_url: "http://80.93.60.49:30429/api/v1"
  db_url: "postgresql://mad:secretPASSW0rd@80.93.60.49:30000/ml_models"

queries:
  - name: "requests_total_2"
    query: 'vm_http_requests_total{path="/api/v1/query_range"}'

metrics:
  - name: "requests_total"
    queries:
      - "requests_total_2"

training:
  models:
    - metric: "requests_total"
      training_period:
        fixed_range:
          start: "2025-07-18T07:28:03Z"
          end: "2025-07-18T08:00:30Z"
          step: "1m"

detection:
  points_anomaly:
    - queries: requests_total # ПС
      delta_threshold: "auto" # ПС
      interpolation: "linear" # ПС
    - queries: requests_total_2 # ПС
      delta_threshold: 65 # ПС
      interpolation: "linear" # ПС
  system_anomaly:
    percentile_threshold: 0.95 # БД
    min_confirmations:
      group_anomaly: 20 # БД
      local_anomaly: 3 # БД
      global_anomaly: 1 # БД

telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN" # БД
  chat_id: "YOUR_TELEGRAM_CHAT_ID" # БД
  message_template: "Обнаружена аномалия! Метрика: {metric}, Время: {timestamp}, Значение: {value}" # БД