# values.yaml
stack:
  # Настройки VictoriaMetrics Single
  enabled: true
  vmselect:
    enabled: true
  vminsert:
    enabled: true
  vmstorage:
    enabled: true

  server:
    enabled: true
    extraScrapeConfigs:
      - job_name: "victoriametrics-self"
        static_configs:
          - targets: ["80.93.60.49:30429"]
        metrics_path: "/metrics"
        scheme: "http"