# VictoriaMetrics конфиг
victoriametrics:
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.91.3
    pullPolicy: IfNotPresent
  retentionPeriod: "1"  # Хранение данных 1 месяц
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

# VMAgent конфиг
vmagent:
  enabled: true
  image:
    repository: victoriametrics/vmagent
    tag: v1.91.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  scrape_interval: "15s"
  nodePort: 30429  # NodePort для доступа к vmagent