stack:
  enabled: true
  vmselect:
    enabled: true
  vminsert:
    enabled: true
  vmstorage:
    enabled: true
  server:
    enabled: true
    scrape:
      enabled: true
      config:
        scrape_configs: []
      extraScrapeConfigs:
        - job_name: 'vmsingle'
          static_configs:
            - targets: ['80.93.60.49:30429']