stack:
  # Отключаем ненужные компоненты
  grafana:
    enabled: false
  alertmanager:
    enabled: false
  prometheusOperator:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false

  # Настройки VictoriaMetrics
  victoria-metrics-operator:
    enabled: true
    vmalert:
      enabled: false  # ← Отключаем vmalert

  victoria-metrics-single:
    enabled: true
    vmselect:
      enabled: true
    vminsert:
      enabled: true
    vmstorage:
      enabled: true