apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-hba
  labels:
    app: postgresql
data:
  # Кастомный pg_hba.conf
  pg_hba.conf: |
    # TYPE  DATABASE  USER  ADDRESS      METHOD
    host    all       all   0.0.0.0/0    trust
    host    all       all   ::/0         trust
    local   all       all                trust