apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: storage
  labels:
    app: postgresql
type: Opaque
data:
  postgres-root-pass: dGVzdDEyMyE=
  GRAFANA_PASSWORD: cmVwbFBhc3MxMjM=
  MAD_PASSWORD: c2VjcmV0UEFTU1cwcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-creds
  namespace: storage
  labels:
    app: postgresql
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |-
    ewogICJhdXRocyI6IHsKICAgICJkb2NrZXIuaW8iOiB7CiAgICAgICJ1c2VybmFtZSI6ICJ2bGFkYWRlcmluYSIsCiAgICAgICJwYXNzd29yZCI6ICJka2ZsZjA1MTAiLAogICAgICAiYXV0aCI6ICJkbXhoWkdGa1pYSnBibUU2Wkd0bWJHWXdOVEV3IgogICAgfQogIH0KfQo=