apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  labels:
    app: postgresql
type: Opaque
data:
  postgres-root-pass: dGVzdDEyMyE=
  GRAFANA_PASSWORD: cmVwbFBhc3MxMjM=
  MAD_PASSWORD: c2VjcmV0UEFTU1cwcmQ=
