apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: istio-metrics
  namespace: monitoring
spec:
  jobName: istio
  kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
          - istio-system
  relabelConfigs:
    - sourceLabels: [__meta_kubernetes_service_label_istio]
      action: keep
      regex: pilot|envoy
    - sourceLabels: [__meta_kubernetes_endpoint_address_target_kind]
      action: keep
      regex: Pod
    - sourceLabels: [__meta_kubernetes_endpoint_address_target_name]
      targetLabel: pod_name
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace