apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: istio-metrics
  namespace: monitoring
spec:
  kubernetesSDConfigs:
    - role: endpoints
      namespaces:
        names:
          - istio-system
  relabelConfigs:
    - sourceLabels: [__meta_kubernetes_service_name]
      action: keep
      regex: istiod
    - sourceLabels: [__meta_kubernetes_endpoint_port_name]
      action: keep
      regex: http-monitoring
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: istio-system