site_name: KubeAnomaly

docs_dir: mkdocs

site_url: https://vladaderina.github.io/KubeAnomaly/

site_description: Документация по проекту KubeAnomaly

site_author: Vlada Derina

repo_url: https://github.com/vladaderina/KubeAnomaly/tree/main

theme:
  name: material
  features:
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle

nav:
  - Описание: index.md
  - Теория:
    - Reverse engineering приложения "E-commerce": e-commerce-theory.md
    - Метрики: metrics.md
    - Основные метрики для мониторинга состояния кластера: metrics_types.md
    - Архитектура HA кластера: architecture.md
    - Компоненты control plane: cp.md
    - Автоматизированное развертывание K8s: k8s-deploy.md
  - Практика:
      - Установка minikube: minikube.md
      - Развертывание с Helm:
        - Приложение "E-commerce": e-commerce-deploy.md
        - Система мониторинга: vm-deploy.md
        - Хранилище: db-deploy.md
      - Terraform: terraform.md
      - Сбор метрик: 
        - Istio: istio.md
        - Метрики kubernetes: control-plane-metrics.md
      - CI/CD: ci-cd.md
      - Анализ аномалий: 
        - Сontrol plane: breakdown1.md



extra_css:
  - css/extra.css

plugins:
  - search
  - table-reader
  - include-markdown
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - attr_list
    - def_list
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - attr_list
    - md_in_html

copyright: Copyright &copy; 2024 <a href="https://t.me/vladaderina">Vlada Derina</a>.
