site_name: KubeAnomalyDocs

docs_dir: mkdocs

site_url: https://vladaderina.github.io/KubeAnomalyDocs/

site_description: Документация по проекту KubeAnomaly

site_author: Vlada Derina

repo_url: https://github.com/vladaderina/KubeAnomalyDocs/tree/main

theme:
  name: material
  features:
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle

nav:
  - Описание: index.md
  - Теория:
    - Метрики: metrics.md
    - Принципы HA кластера: ha.md
    - Компоненты control plane: cp.md
  - Тестовое окружение:
      - Кластер в MiniKube: 
        - Развертывание: MiniKube.md
        - Моделируем поломку: breakdown1.md
      - Кластер HA:
        - Развертывание:
          - Архитектура кластера: architecture.md 
          - Автоматизированное развертывание VM: vm-deploy.md
          - Автоматизированное развертывание K8s: k8s-deploy.md

extra_css:
    - css/extra.css

plugins:
  - search
  - table-reader

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - attr_list
    - def_list
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - attr_list
    - md_in_html

copyright: Copyright &copy; 2024 <a href="https://t.me/vladaderina">Vlada Derina</a>.
