version: '3.8'

services:
  collector:
    build: ./1-collector-service
    volumes:
      - ./1-collector-service/config:/app/config
      - ./data:/app/data
    environment:
      DB_HOST: 80.93.60.49
    networks:
      - monitoring

  model-service:
    build: ./2-model-service
    ports:
      - "8000:8000"
    environment:
      DB_DSN: "postgresql://mad:secretPASSW0rd@80.93.60.49/ml_models"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge