name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed directories
        id: changes
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD -- KubeAnomaly/KubeAnomaly/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Detect changed services
        id: changed-services
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD)
          services=$(echo "$changed_files" | awk -F/ '{print $1}' | sort | uniq)
          echo "::set-output name=services::$(echo $services | tr '\n' ' ')"

      - name: Build and push Docker images
        run: |
          for service in ${{ steps.changed-services.outputs.services }}; do
            if [ -d "src/$service" ]; then
              docker build -t ${{ env.DOCKER_HUB_USERNAME }}/$service:latest ./$service
              docker push ${{ env.DOCKER_HUB_USERNAME }}/$service:latest
            fi
          done

      - name: Deploy to Kubernetes
        run: |
          helm upgrade my-microservices ./helm/ \
            --kubeconfig ~/.kube/kubeconfig-github