name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: minikube
    env: 
      DOCKER_HUB_USERNAME: ${{ vars.DOCKER_HUB_USERNAME }} 
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect changed services
        id: changed-services
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD)
          services=$(echo "$changed_files" | awk -F/ 'NF >= 3 {print $2}' | sort | uniq)
          echo $services
          echo "services=$(echo $services | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          for service in ${{ steps.changed-services.outputs.services }}; do
            if [ -d "src/$service" ]; then
              docker build -t ${{ env.DOCKER_HUB_USERNAME }}/$service:$GITHUB_SHA ./src/$service
              docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ env.DOCKER_HUB_TOKEN }}
              docker push ${{ env.DOCKER_HUB_USERNAME }}/$service:$GITHUB_SHA
            fi
          done

      - name: Tags owerrides
        run: |
          for service in ${{ steps.changed-services.outputs.services }}; do
            if [ -d "src/$service" ]; then
              yq -i '.Values.$service.tag="$GITHUB_SHA"' values.yaml
            fi
          done

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --kubeconfig ~/.kube/kubeconfig-github my-microservices ./helm/