name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Detect changed services
        id: changed-services
        run: |
          changed_files=$(git diff --name-only HEAD^ HEAD)
          services=$(echo "$changed_files" | awk -F/ 'NF >= 3 {print $2}' | sort | uniq)
          echo $services
          echo "services=$(echo $services | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        run: |
          for service in ${{ steps.changed-services.outputs.services }}"; do
            if [ -d "src/$service" ]; then
              docker build -t ${{ env.DOCKER_HUB_USERNAME }}/$service:latest ./src/$service
              docker login -u ${{ env.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
              docker push ${{ env.DOCKER_HUB_USERNAME }}/$service:latest
            fi
          done

      - name: Deploy to Kubernetes
        run: |
          helm upgrade my-microservices ./helm/ \
            --kubeconfig ~/.kube/kubeconfig-github